/**
 * Workflow v1 → v2 migration + light validation helpers.
 *
 * No runtime executor lives here — just the shape conversion and structural
 * checks. See docs/workflow-design.md for the full design.
 */
import type {
  ActionNode,
  Workflow,
  WorkflowNode,
  WorkflowV2,
} from '../types/workflow';

const NODE_ID_RE = /^[a-z0-9_-]+$/;

/** Throws a descriptive Error if the workflow is structurally invalid. */
export function validateWorkflowV2(wf: WorkflowV2): void {
  if (wf.version !== 2) {
    throw new Error(`workflow ${wf.id}: expected version 2, got ${wf.version}`);
  }
  if (!wf.entry) {
    throw new Error(`workflow ${wf.id}: missing required field "entry"`);
  }
  if (!wf.nodes || Object.keys(wf.nodes).length === 0) {
    throw new Error(`workflow ${wf.id}: must define at least one node in "nodes"`);
  }
  if (!wf.nodes[wf.entry]) {
    throw new Error(
      `workflow ${wf.id}: entry node "${wf.entry}" not found in nodes`,
    );
  }
  for (const [id, node] of Object.entries(wf.nodes)) {
    if (id !== node.id) {
      throw new Error(
        `workflow ${wf.id}: node key "${id}" does not match node.id "${node.id}"`,
      );
    }
    if (!NODE_ID_RE.test(id)) {
      throw new Error(
        `workflow ${wf.id}: node id "${id}" must match ${NODE_ID_RE}`,
      );
    }
    validateNode(wf.id, node);
  }
}

function validateNode(workflowId: string, node: WorkflowNode): void {
  switch (node.type) {
    case 'action':
      if (!node.description) {
        throw new Error(`${workflowId}/${node.id}: action requires description`);
      }
      if (!node.query) {
        throw new Error(`${workflowId}/${node.id}: action requires query`);
      }
      return;
    case 'wait':
    case 'note':
      return;
    case 'branch':
      if (!node.default) {
        throw new Error(
          `${workflowId}/${node.id}: branch requires a "default" goto target`,
        );
      }
      if (!node.branches?.length) {
        throw new Error(
          `${workflowId}/${node.id}: branch must define at least one branch`,
        );
      }
      return;
    case 'parallel':
      if (!node.all?.length) {
        throw new Error(
          `${workflowId}/${node.id}: parallel must define at least one child`,
        );
      }
      return;
    case 'loop':
      if (!node.body) {
        throw new Error(`${workflowId}/${node.id}: loop requires body`);
      }
      if (!node.itemParam) {
        throw new Error(`${workflowId}/${node.id}: loop requires itemParam`);
      }
      return;
    case 'subworkflow':
      if (!node.ref) {
        throw new Error(`${workflowId}/${node.id}: subworkflow requires ref`);
      }
      return;
  }
}

/**
 * Migrate a v1 linear workflow to a v2 DAG workflow.
 *
 * - v1: `{ id, title, steps: [{ step, title, description, query, hint }] }`
 * - v2: `{ id, title, entry, nodes: { "step-1": action, ... } }`
 *
 * Idempotent: a workflow that already has `version: 2` is returned as-is.
 */
export function migrateV1ToV2(wf: Workflow): WorkflowV2 {
  if (wf.version === 2) {
    // Already v2 — coerce to WorkflowV2 (runtime uses the same shape).
    return {
      id: wf.id,
      title: wf.title,
      description: wf.description,
      page: wf.page,
      estimatedTime: wf.estimatedTime,
      version: 2,
      entry: wf.entry ?? '',
      nodes: wf.nodes ?? {},
      steps: wf.steps,
      metadata: wf.metadata,
    };
  }

  if (!wf.steps?.length) {
    throw new Error(`workflow ${wf.id}: no steps to migrate`);
  }

  const nodes: Record<string, WorkflowNode> = {};
  // Each legacy step becomes an `action` node. The runtime's executor should
  // detect the `linear_chain` node and walk `steps` in numeric order (see
  // docs/workflow-design.md §Backward compatibility). For the v2 topological
  // walk, we still produce a parallel grouping so all actions are reachable
  // from `entry`.
  wf.steps.forEach((step) => {
    const id = `step-${step.step}`;
    const action: ActionNode = {
      id,
      type: 'action',
      title: step.title,
      description: step.description,
      query: step.query,
    };
    if (step.hint !== undefined) action.hint = step.hint;
    nodes[id] = action;
  });
  const orderedChildren = wf.steps.map((s) => `step-${s.step}`);
  nodes.linear_chain = {
    id: 'linear_chain',
    type: 'parallel',
    title: 'Execute steps in order',
    description: 'Auto-generated by v1→v2 migration. Runtime should walk steps in numeric order.',
    all: orderedChildren,
    waitFor: 'all',
    failFast: true,
  };

  return {
    id: wf.id,
    title: wf.title,
    description: wf.description,
    page: wf.page,
    estimatedTime: wf.estimatedTime,
    version: 2,
    entry: `step-${wf.steps[0].step}`,
    nodes,
    steps: wf.steps,
    metadata: wf.metadata,
  };
}

/** Detect if a workflow is already on v2 (i.e. uses the nodes graph). */
export function isV2Workflow(wf: Workflow): wf is WorkflowV2 {
  return wf.version === 2 && !!wf.nodes && !!wf.entry;
}

/** Walk the workflow graph from `entry` and yield nodes in topological order. */
export function* topologicalNodes(
  wf: WorkflowV2,
): Generator<WorkflowNode, void, void> {
  const visited = new Set<string>();
  const stack: string[] = [wf.entry];
  while (stack.length > 0) {
    const id = stack.pop()!;
    if (visited.has(id)) continue;
    visited.add(id);
    const node = wf.nodes[id];
    if (!node) continue;
    yield node;
    // Push successors (children) for the common control-flow nodes.
    if (node.type === 'branch') {
      stack.push(node.default);
      for (const b of node.branches) stack.push(b.goto);
    } else if (node.type === 'parallel') {
      for (const child of node.all) stack.push(child);
    } else if (node.type === 'loop') {
      stack.push(node.body);
    }
  }
}
